import json
from pathlib import Path

from ai_modules.rag_system.schemas import DocumentInput, LegalInfo

# Path to demo data folder
DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "demo"


def load_member1_data() -> DocumentInput:
    """
    Load demo data generated by Member 1
    """

    file_path = DATA_DIR / "member1.json"

    with open(file_path, "r", encoding="utf-8") as file:
        data = json.load(file)

    return DocumentInput(**data)


def load_member2_data() -> LegalInfo:
    """
    Load demo data generated by Member 2
    """

    file_path = DATA_DIR / "member2.json"

    with open(file_path, "r", encoding="utf-8") as file:
        data = json.load(file)

    return LegalInfo(**data)


def load_demo_data():
    """
    Returns both demo inputs.
    """

    return load_member1_data(), load_member2_data()